# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Unit.create(unit_number: 101)
Unit.create(unit_number: 102)
Unit.create(unit_number: 103)
Unit.create(unit_number: 104)
Unit.create(unit_number: 105)
Unit.create(unit_number: 106)
Unit.create(unit_number: 107)
Unit.create(unit_number: 108)
Unit.create(unit_number: 109)
Unit.create(unit_number: 110)
Unit.create(unit_number: 111)
Unit.create(unit_number: 201)
Unit.create(unit_number: 202)
Unit.create(unit_number: 203)
Unit.create(unit_number: 204)
Unit.create(unit_number: 205)
Unit.create(unit_number: 206)
Unit.create(unit_number: 207)
Unit.create(unit_number: 208)
Unit.create(unit_number: 209)
Unit.create(unit_number: 210)
Unit.create(unit_number: 211)
Unit.create(unit_number: 301)
Unit.create(unit_number: 302)
Unit.create(unit_number: 303)
Unit.create(unit_number: 304)
Unit.create(unit_number: 305)
Unit.create(unit_number: 306)
Unit.create(unit_number: 307)
Unit.create(unit_number: 308)
Unit.create(unit_number: 309)
Unit.create(unit_number: 310)
Unit.create(unit_number: 311)

UserType.create()
